server:
  port: 10086

spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/center_manager_sys?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/quick_batch?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  redis:
    database: 8
    host: 120.78.153.10
    port: 6379
    password: badguy
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

  #不加这个会出现 Spring Data Redis - Could not safely identify store assignment for repository candidate interface
  data:
    redis:
      repositories:
        enabled: false

weChat:
  appId: wxece569f498719ea0
  appSecret: 69e7c579c573d343bcf681d67033e9b7

qiNiu:
  accessKey: 3P4RflUg3YzzXFrFiCVo6_CCpfPlaBIIxoP5H7C-
  secretKey: k_e5DcLCwo01oO__dv2rlXnddSIuL7jWjPcA8dQn
  bucket: badguy
  domain: https://qiniu.great-info.tech/

lottery:
  rule1: 1/0.005,2/0.01,3/0.005,4/0,5/0,6/0,7/0.49,8/0.49
  rule2: 1/0,2/0.005,3/0,4/0.005,5/0,6/0,7/0.495,8/0.495
  rule3: 1/0,2/0,3/0,4/0,5/0.025,6/0.1,7/0.4375,8/0.4375
